### PR TITLE
[WIP] Tests for CPS tax unit benefit data

### PR DESCRIPTION
**Pull request by Amy-Xu**
This PR intends to provide a test script that checks distribution and aggregates information as outlined in [taxdata issue #115](https://github.com/open-source-economics/taxdata/issues/115). The current draft script generates three files:

1. `decile2015.csv` includes decile participation and benefit tables for each program for year 2015.
2. `aggregates.txt` includes participation (tax units & individual) and benefit totals from 2014 to 2024. 
3. `tabs.txt` includes tabulation of tax-unit participation from year 2014 to 2024.

This script will compare new results with existing files once it's finished. However, there is one dilemma I found when writing the script. In order to calculate decile participation and benefits, we need at least the wage and weight information from the original CPS tax unit dataset. Possibly more income variables depending on what decile we want in the end. The ten year aggregate table also needs the extrapolated weight file prepared for CPS tax unit. But neither the CPS tax unit nor the weight file is in this repo, or supposed to be in this repo. Given the discussion in [TC issue #1500](https://github.com/open-source-economics/Tax-Calculator/pull/1500), it seems this repo will for sure host `cps_benefit.csv`. 

So while I'm finishing up the script, it would be great to hear more input on what the best location is for this script, or how to improve the current testing situation.

@martinholmer @MattHJensen @hdoupe @andersonfrailey

### CODE REVIEW

**Comment by martinholmer** [comment]
@Amy-Xu,  I have a couple of questions about pull request #1 in the `tax-unit_benefit` repo.

First, why is the `cps_benefits.csv.gz` file included in the pull request?  Isn't that file created, and therefore, under version control in some other repository?  Where is it generated?  In the `C-TAM` repo or in the `taxdata` repo or somewhere else?  There should be only **one** version of the file under version control.  Any other repository that needs to use the `cps_benefits.csv.gz` file can have it as an unversioned file, just like the Tax-Calculator and PolicyBrain repos have a copy of the `puf.csv` file that is not under version control.

Second, can't you simply have a copy of the `cps.csv.gz` file in this repo for use by our scripts, but (just like `puf.csv`) don't put it under version control in this repo because its already under version control in the `taxdata` repository?  Would this approach meet all your needs?

@MattHJensen @andersonfrailey @hdoupe

**Comment by Amy-Xu** [comment]
@martinholmer asked:

>First, why is the cps_benefits.csv.gz file included in the pull request? Isn't that file created, and therefore, under version control in some other repository? Where is it generated? In the C-TAM repo or in the taxdata repo or somewhere else? 

In TC issue #1500, it seems to me that you [proposed](https://github.com/open-source-economics/Tax-Calculator/pull/1500#issuecomment-328121714) to put `cps_benefit.csv.gz` in a separate conda package and everyone [agreed](https://github.com/open-source-economics/Tax-Calculator/pull/1500#issuecomment-328186336) with this approach. Hence, Matt [created](https://github.com/open-source-economics/Tax-Calculator/pull/1500#issuecomment-333681537) this repo for this CPS benefit file. Is having this file in its own conda package still your preference at this point?

This file is generated in taxdata [PR #108](https://github.com/open-source-economics/taxdata/pull/108/files). According to the discussion in TC issue #1500, I expect we would eventually need to move the benefit data file to this repo, and start the version control of this file in this repo.

>Second, can't you simply have a copy of the cps.csv.gz file in this repo for use by our scripts, but (just like puf.csv) don't put it under version control in this repo because its already under version control in the taxdata repository?

That defnitely works for me at this point. I just wonder whether it might be slightly inconvenient for users -- when they want to run the test, they will have to download two other datasets from a different repo.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> In [TC issue 1500](https://github.com/open-source-economics/Tax-Calculator/pull/1500), it seems to me that you proposed to put `cps_benefit.csv.gz` in a separate **conda package** and everyone agreed with this approach. Hence, Matt created **this repo** for this CPS benefit file. Is having this file in its own **conda package** still your preference at this point?
>
> This file is generated in [taxdata PR 108](https://github.com/open-source-economics/taxdata/pull/108). 

@Amy-Xu also said:
> According to the discussion in [TC issue 1500](https://github.com/open-source-economics/Tax-Calculator/pull/1500), I expect we would eventually need to move the benefit data file to this repo, and start the version control of this file in this repo.

First, there is a big conceptual difference between a **GitHub repository** and a **conda package**.

Second, yes, I continue to think putting the `cps_benefit.csv.gz` in its own **conda package** makes sense.  But why not generate the conda package where the `cps_benefit.csv.gz` file is generated and is under version control in the taxdata repository?   (Putting `cps_benefit.csv.gz` under version control is part of the proposed [taxdata PR 108](https://github.com/open-source-economics/taxdata/pull/108)).

And third, why not put this `cps_benefit.csv.gz` test script in the appropriate taxdata directory, where the file is generated.  Then you have available in the taxdata repo all the files you need for this test script, right?
Why not test the data right where it is generated?  That makes sense to me.  Then you can add what you need to the taxdata repo to build and upload to www.anaconda.org the public conda package containing the `cps_benefit.csv.gz` file.  This conda package can go in the ospc channel along with the other publicly available packages (taxcalc, btax, ogusa).  There is somewhere in the maze of OSPC repositories a script that creates a private conda package containing the `puf.csv` file.  My guess is that script would provide you a guide about how to generate a public conda package containing the `cps_benefit.csv.gz`  file.  For the details on releasing public conda packages, see the [policybrain-builder repository](https://github.com/open-source-economics/policybrain-builder).

Does this approach make sense?

@MattHJensen @andersonfrailey @hdoupe @GoFroggyRun

**Comment by Amy-Xu** [comment]
@martinholmer Thank you very much for this detailed explanation. Most things make sense to me. I'll go to the private repo for puf.csv and see how to create a conda package, which I'm not familiar with at this point. Then I'll move the testing script and files to taxdata repo. 

@MattHJensen It seems to me that we may not need this repo. But I'll look into conda package a bit more and get back to you.

**Comment by Amy-Xu** [comment]
Since the dataset is currently in [taxdata](https://github.com/open-source-economics/taxdata/tree/master/cps_stage3) repo, I'm closing this PR and open a new PR with updated files in taxdata.

@MattHJensen We may not need this repo any more.

cc @martinholmer

**Comment by MattHJensen** [comment]
Thanks @Amy-Xu. I will delete this repo.

**Pull request closed without merging**
